version: '3.8'

services:
  teslodb:
    container_name: teslodb
    hostname: teslodb
    image: postgres:14.3
    ports:
      - "54321:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data/